options:
  logging: CLOUD_LOGGING_ONLY

steps:
# Build the container image
# docker build -t us-east1-docker.pkg.dev/flashcard-429516/flashcard/flashcard-cloudrun:$COMMIT_SHA -f Dockerfile.cloudrun .
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-east1-docker.pkg.dev/flashcard-429516/flashcard/flashcard-cloudrun-image:$COMMIT_SHA', '-f', 'dockerfile.cloudrun', '.']
  id: 'Build Flask App Container'

# Push the container image to Artifact Registry
# docker push us-east1-docker.pkg.dev/flashcard-429516/flashcard/flashcard-cloudrun:$COMMIT_SHA
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east1-docker.pkg.dev/flashcard-429516/flashcard/flashcard-cloudrun-image:$COMMIT_SHA']
  id: 'Push to artifact Registery'

# Deploy container image to Cloud Run
#  gcloud run deploy flashcard-app \
#   --image us-east1-docker.pkg.dev/flashcard-429516/flashcard/flashcard-cloudrun:$COMMIT_SHA \
#   --region us-east1 \
#   --platform managed \
#   --allow-unauthenticated \
#   --set-secrets PERPLEXITY_API_KEY=perplexity-api-key:latest,OPENAI_API_KEY=openai-api-key:latest
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'flashcard-app-image'
  - '--image'
  - 'us-east1-docker.pkg.dev/flashcard-429516/flashcard/flashcard-cloudrun-image:$COMMIT_SHA'
  - '--region'
  - 'us-east1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--set-secrets'
  - 'PERPLEXITY_API_KEY=perplexity-api-key:latest,OPENAI_API_KEY=openai-api-key:latest'
  - '--set-env-vars'
  - 'GOOGLE_CLOUD_ENABLE_CORS=true'
  - '--cors-allow-origin=*'
  - '--cors-allow-methods=GET,POST,PUT,DELETE,OPTIONS'
  - '--cors-allow-headers=Content-Type,Authorization'
  id: 'Deploy to Cloud Run'

images:
- 'us-east1-docker.pkg.dev/flashcard-429516/flashcard/flashcard-cloudrun-image:$COMMIT_SHA'